name: Issue Notification

on:
  issues:
    types: [opened]

jobs:
  issue-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send issue notification
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Bonjour ${{ github.actor }}"
          echo "Nous avons bien pris en compte votre problème du nom de : ${{ github.event.issue.title }}"
